# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gjk19/Desktop/Digital Circuit/Vivado Project/RISC CPU/RISC CPU.srcs/sources_1/ip/rom_256x16b/rom_256x16b.xci
# IP: The module: 'rom_256x16b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gjk19/Desktop/Digital Circuit/Vivado Project/RISC CPU/RISC CPU.srcs/sources_1/ip/rom_256x16b/rom_256x16b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_256x16b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/gjk19/Desktop/Digital Circuit/Vivado Project/RISC CPU/RISC CPU.srcs/sources_1/ip/rom_256x16b/rom_256x16b.xci
# IP: The module: 'rom_256x16b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gjk19/Desktop/Digital Circuit/Vivado Project/RISC CPU/RISC CPU.srcs/sources_1/ip/rom_256x16b/rom_256x16b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_256x16b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
